### ISSUE TITLE
THIS NO LONGER WORKES ANYMORE! PLEASE FIX! 404

### ISSUE THREAD

**Issue by 03stevensmi** [richardg867/WaybackProxy#19]
Right, now its broken.
Nothing from the dev but now its not working at all.
Been at this crap for 2 straight days.
2022-09-22
Raspberry pi 32bit bullseye

Everything I load any page up I get this:

pi@raspberrypi:~ $ sudo python3 ./WaybackProxy/waybackproxy.py
[-] Now listening on port 8888
[>] http://home.netscape.com/
[>] http://home.netscape.com/images/home_igloo.jpg
[>] http://home.netscape.com/_static/js/bundle-playback.js?v=21L7o4JU
[>] http://home.netscape.com/images/nav_home.gif
[>] http://home.netscape.com/inserts/images/n_sm.gif
[!] 404 NOT FOUND
[>] http://home.netscape.com/
[>] http://home.netscape.com/inserts/images/n_sm.gif
[>] http://home.netscape.com/images/nav_home.gif
[>] http://home.netscape.com/_static/js/bundle-playback.js?v=21L7o4JU
[>] http://home.netscape.com/inserts/images/bullet_sm.gif
[>] http://home.netscape.com/inserts/images/jimb_sm.gif
[>] http://home.netscape.com/inserts/images/tuneup.gif
[!] 404 NOT FOUND
----------------------------------------
Exception occurred during processing of request from ('192.168.1.131', 57627)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/pi/./WaybackProxy/waybackproxy.py", line 399, in handle
    self.send_passthrough(conn, http_version, content_type, request_url)
  File "/home/pi/./WaybackProxy/waybackproxy.py", line 408, in send_passthrough
    self.request.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------

Any help at all?

**Comment by 03stevensmi** [comment]
Now I get this on internet explorer:


[-] Now listening on port 8888
[-] Date set to 20011025
[>] http://home.netscape.com/
[>] http://home.netscape.com/_static/js/bundle-playback.js?v=21L7o4JU
[>] http://home.netscape.com/images/home2001c/m0.gif
[>] http://home.netscape.com/images/x.gif
[>] http://home.netscape.com/images/x.gif
[>] http://home.netscape.com/ex/shak/home2001c/images/hp_shortcuts_a.gif
[>] http://home.netscape.com/ex/shak/home2001c/images/nslogo_t.gif
[!] 404 NOT FOUND
[>] http://home.netscape.com/ex/shak/images/bar_un/missy1.gif
[>] http://yahoo.com/
[>] http://us.a1.yimg.com/us.yimg.com/a/ya/yahoomail/promo1.gif
[>] http://us.a1.yimg.com/us.yimg.com/i/ww/m5v5.gif
[>] http://yahoo.com/_static/js/bundle-playback.js?v=21L7o4JU
[!] 404 NOT FOUND
[>] http://yahoo.com/_static/js/bundle-playback.js?v=21L7o4JU
[!] 404 NOT FOUND
^Cpi@raspberrypi:~/waybackproxy $ sudo nano config.json
pi@raspberrypi:~/waybackproxy $ sudo nano config_handler.py
pi@raspberrypi:~/waybackproxy $ python3 waybackproxy.py
[-] Now listening on port 8811
[-] Date set to 19960510
[>] http://home.microsoft.com/
[>] http://yahoo.com/
[!] Fetch exception:
Traceback (most recent call last):
  File "/home/pi/waybackproxy/waybackproxy.py", line 188, in handle
    conn = urllib.request.urlopen(request_url)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by KrazeeTobi** [comment]
IA recently updated their scripts, breaking the proxy in the process. This is probably part of the problem.

**Comment by NTxC** [comment]
If I may suggest, please try to fix this problem. This script makes browsing the old web so much better.

**Comment by richardg867** [comment]
I've updated the script removal code, but the stack traces suggest you either have connection issues to the Wayback Machine or you're just not patient enough. Cannot reproduce.
